### ISSUE TITLE
Clear symbol when former selection is active provokes an index error

### ISSUE THREAD

**Issue by wawachief** [wawachief/DigiQt#14]
Traceback (most recent call last):
  File "/home/wawa/src/DigiQt/src/view/SymbolViewFrame.py", line 111, in on_label_changed
    print(self.__retrieve_text(self.dm_labels, item))
  File "/home/wawa/src/DigiQt/src/view/SymbolViewFrame.py", line 129, in __retrieve_text
    return data_model.item(QModelIndex(item.indexes()[0]).row()).text()
IndexError: list index out of range

**Comment by ThomasLecluse** [comment]
Fixed
